//! Copyright 2026 Eric Kryski (@ekryski) and Tom Turney (@TheTom)
//! SPDX-License-Identifier: Apache-2.0
//! CUDA codegen backend (CUDA_BACKEND_SPEC §4.2 / SCOPE Phases 1–4).
//!
//! Lowers the backend-neutral algorithm IR to CUDA C++ (compiled at
//! runtime via NVRTC, or offline via `nvcc`). Shares the IR, the
//! `#[kernel]` macro, and the entire `quant::{codec,format}` layer with
//! the Metal path — only the leaf text differs, captured in
//! [`TargetProfile`](crate::backend::TargetProfile).
//!
//! **Status: Phase 1 — elementwise smoke subset.** `generate` emits CUDA
//! C++ for `KernelMode::Elementwise` kernels using the ops
//! `ProgramId / Const / Load / Store / BinOp / UnaryOp / Cast / Fma`.
//! That covers the `copy` / `vector_add` smoke kernels end-to-end
//! (NVRTC compile + launch on the GX10 / sm_121). Reductions,
//! simdgroup/MMA, coop_tile, and `InlineMsl` return `UnsupportedOp`
//! pending Phases 2–5.
//!
//! Strategy note (SCOPE §6 — decided): do NOT fork `msl/emit_block.rs`
//! (61 KB) up front. This is a fresh, minimal op-walker for the Phase-1
//! subset; it grows per phase. A shared backend-neutral walker is only
//! extracted once both emitters exist and the common structure is
//! empirically clear — premature extraction risks the wrong abstraction
//! over a hot path.
//!
//! Phase-1 deliberate simplifications (tracked for Phase 2):
//! - No optimization passes run yet (the pipeline is backend-neutral but
//!   can introduce `FusedElementwise`/`Fma` ops the smoke walker doesn't
//!   handle). Smoke kernels emit correctly from raw IR.
//! - A trailing `unsigned int _n_elems` param + an `if (gtid >= _n_elems)
//!   return;` guard replace Metal's non-uniform-threadgroup bounds model.

use std::{collections::BTreeMap, fmt::Write as _};

use wh_iron_core::{
    dtype::DType,
    ir::{
        ActKind,
        AtomicKind,
        BinOpKind,
        Block,
        CoopTileAccMode,
        CoopTileScope,
        IndexExpr,
        Kernel,
        KernelMode,
        Op,
        Param,
        ParamKind,
        ReduceKind,
        UnaryOpKind,
        ValueId,
    },
};

use crate::{
    Result,
    backend::{CodegenBackend, Target, TargetProfile},
    error::Error,
};

/// Shared preamble for every emitted CUDA kernel: headers, the `IRON_INF`
/// constant (NVRTC has no `INFINITY` macro), and the block-scaled-quant
/// decode helpers ported verbatim from `msl/preamble.rs` (pure arithmetic
/// → identical to `kernels::quant::codec`). Unused helpers are pruned by the
/// compiler, so we always emit them.
const CUDA_PREAMBLE: &str = r#"// Generated by Iron Kernels (CUDA backend). DO NOT EDIT.
#include <cuda_fp16.h>
#include <cuda_bf16.h>
// +inf without pulling <math_constants.h> (NVRTC-safe). NVRTC has no
// INFINITY macro, so alias it too (kernels emit literal INFINITY for masks).
#define IRON_INF (__int_as_float(0x7f800000))
#ifndef INFINITY
#define INFINITY IRON_INF
#endif

// E2M1 (fp4): codebook {0,.5,1,1.5,2,3,4,6}, sign in bit 3.
__device__ __forceinline__ float iron_decode_e2m1(unsigned int code) {
    unsigned int m = code & 7u;
    float mag = (m < 1u) ? 0.0f : (m < 2u) ? 0.5f : (m < 3u) ? 1.0f : (m < 4u) ? 1.5f
              : (m < 5u) ? 2.0f : (m < 6u) ? 3.0f : (m < 7u) ? 4.0f : 6.0f;
    return (code & 8u) ? -mag : mag;
}
// E4M3 (fp8): (1+m/8)*2^(e-7); subnormal m*2^-9; sign in bit 7.
__device__ __forceinline__ float iron_decode_e4m3(unsigned int bits) {
    unsigned int e = (bits >> 3u) & 15u;
    unsigned int m = bits & 7u;
    float mag = (e < 1u) ? ((float)m * 0.001953125f)
              : ((1.0f + (float)m * 0.125f) * exp2f((float)e - 7.0f));
    return ((bits >> 7u) & 1u) ? -mag : mag;
}
// E5M2 (fp8): (1+m/4)*2^(e-15); subnormal m*2^-16; sign in bit 7.
__device__ __forceinline__ float iron_decode_e5m2(unsigned int bits) {
    unsigned int e = (bits >> 2u) & 31u;
    unsigned int m = bits & 3u;
    float mag = (e < 1u) ? ((float)m * 0.0000152587890625f)
              : ((1.0f + (float)m * 0.25f) * exp2f((float)e - 15.0f));
    return ((bits >> 7u) & 1u) ? -mag : mag;
}
// Symmetric int8: reinterpret the byte as i8 (sign-extend low 8 bits).
__device__ __forceinline__ float iron_decode_int8(unsigned int bits) {
    return (float)((int)(bits << 24u) >> 24);
}

// Precise float divide via Markstein refinement. Plain `a / b` on AMDGPU
// hipRTC compiles to `V_RCP_F32 + V_MUL_F32` which can be 1 ULP off the
// correctly-rounded result. One Newton-Raphson step on top of the
// hardware reciprocal gives a correctly-rounded f32 quotient (relies on
// `V_FMAC_F32` being correctly rounded — AMDGPU guarantees this). Used
// when `TargetProfile::precise_simd_sum` (the precision-bundle flag) is
// on (HIP profile turns it on; CUDA leaves it off and stays on `a / b`).
//
// The general template falls through to `a / b` so integer / mixed-type
// divides (`auto v = iron_fdiv(int, int)` for SSA index math, `iron_fdiv(uint,
// int)` after C++ promotion) preserve their natural type — only the
// explicit `float, float` specialisation engages the Markstein step.
template <typename A, typename B>
__device__ __forceinline__ auto iron_fdiv(A a, B b) -> decltype(a / b) { return a / b; }
template <>
__device__ __forceinline__ float iron_fdiv<float, float>(float a, float b) {
    float r = 1.0f / b;
    float q = a * r;
    float err = __fmaf_rn(-b, q, a);
    return __fmaf_rn(err, r, q);
}
// Refined reciprocal square root. AMD's `V_RSQ_F32` is ~1.4 ULP; one
// Newton-Raphson step tightens it to ≤1 ULP. Same flag as `iron_fdiv`.
__device__ __forceinline__ float iron_rsqrt(float x) {
    float r = rsqrtf(x);
    return r * __fmaf_rn(-0.5f * x * r, r, 1.5f);
}
// f32 exp/log that match Vulkan's `exp`/`log` rounding on AMD. The GLSL
// `exp(x)` on AMD compiles to `exp2(x * log2(e))`; OCML's `expf(x)` uses
// a different range reduction + polynomial. Matching the two-step exp2/
// log2 form keeps the GPU result on the same rounding trajectory as the
// Vulkan backend (and, empirically, the Rust f32::exp on Windows). Used
// only when `TargetProfile::precise_simd_sum` is on — HIP enables, CUDA
// stays on the native `expf` / `logf`.
__device__ __forceinline__ float iron_expf(float x) { return exp2f(x * 1.4426950408889634f); }
__device__ __forceinline__ float iron_logf(float x) { return log2f(x) * 0.6931471805599453f; }

// Neural activations (ported from msl/preamble.rs).
__device__ __forceinline__ float iron_silu(float x) { return x / (1.0f + expf(-x)); }
__device__ __forceinline__ float iron_relu(float x) { return fmaxf(0.0f, x); }
__device__ __forceinline__ float iron_sigmoid(float x) { return 1.0f / (1.0f + expf(-x)); }
__device__ __forceinline__ float iron_gelu(float x) {
    const float k = 0.7978845608f;
    float arg = k * (x + 0.044715f * x*x*x);
    arg = fminf(fmaxf(arg, -15.0f), 15.0f);
    return 0.5f * x * (1.0f + tanhf(arg));
}

"#;

/// Name of the synthetic element-count param appended to every emitted
/// CUDA kernel (drives the bounds guard). Chosen to not collide with DSL
/// param names.
pub const N_ELEMS_PARAM: &str = "_n_elems";

/// SSA value-name override map (loop vars + parent-block names) threaded
/// into nested Loop/If body emission. See `CudaGenerator::vname`.
type Names = BTreeMap<ValueId, String>;

/// CUDA C++ generator. Mirror of `msl::MslGenerator` for the NVIDIA target.
#[derive(Debug, Clone)]
pub struct CudaGenerator {
    profile: TargetProfile,
}

impl Default for CudaGenerator {
    fn default() -> Self { Self::new() }
}

impl CudaGenerator {
    pub fn new() -> Self { CudaGenerator { profile: TargetProfile::cuda() } }

    /// Build a generator pinned to a specific profile (e.g. a Blackwell
    /// profile with `MmaStrategy::Tcgen05` for Phase 4).
    pub fn with_profile(profile: TargetProfile) -> Self {
        debug_assert_eq!(profile.target, Target::Cuda);
        CudaGenerator { profile }
    }

    // ── SSA value naming (mirrors msl helpers::vname) ──────────────────
    // `ov` is the name-override map: loop-induction vars and parent-block
    // SSA names introduced when recursing into nested Loop/If bodies. It is
    // consulted before the block's own name hints (matches MSL's
    // `extra_names`).
    fn vname(&self, vid: Option<ValueId>, block: &Block, ov: &Names) -> String {
        match vid {
            Some(v) => {
                if let Some(n) = ov.get(&v) {
                    return n.clone();
                }
                // Include the ValueId so distinct SSA values that share a
                // name hint (e.g. a running-max fold reusing `m0`) get
                // UNIQUE C identifiers — otherwise they'd redeclare/self-init.
                match block.names.get(&v) {
                    Some(hint) => format!("v_{hint}_{}", v.as_u32()),
                    None => format!("v{}", v.as_u32()),
                }
            },
            None => "/*<no-value>*/".to_string(),
        }
    }

    // ── Flat index expression for Load/Store ──────────────────────────
    // Multi-dim indices flatten to a single offset: Strided params use
    // their runtime `{src}_strides[d]`; plain tensors use compile-time
    // row-major strides from the param's static shape.
    fn emit_idx(
        &self,
        indices: &[IndexExpr],
        block: &Block,
        ov: &Names,
        kernel: &Kernel,
        src: &str,
    ) -> Result<String> {
        match indices {
            [] => Ok(String::new()),
            [one] => Ok(self.idx_term(one, block, ov)),
            many => {
                let param = kernel.params.iter().find(|p| p.name == src);
                let strided = matches!(param.map(|p| &p.kind), Some(ParamKind::Strided));
                if strided {
                    let terms: Vec<String> = many
                        .iter()
                        .enumerate()
                        .map(|(d, ix)| {
                            format!("({}) * {src}_strides[{d}]", self.idx_term(ix, block, ov))
                        })
                        .collect();
                    return Ok(terms.join(" + "));
                }
                // Row-major: stride[d] = product of static dims after d.
                let shape = param.map(|p| &p.shape).ok_or_else(|| {
                    Error::UnsupportedOp(format!("cuda: multi-dim index on unknown param `{src}`"))
                })?;
                let rank = shape.rank();
                if rank < many.len() {
                    return Err(Error::UnsupportedOp(format!(
                        "cuda: multi-dim index rank mismatch on `{src}`"
                    )));
                }
                let mut terms = Vec::new();
                for (d, ix) in many.iter().enumerate() {
                    let mut stride: u64 = 1;
                    for s in (d + 1)..rank {
                        match shape.dim(s) {
                            Some(wh_iron_core::shape::Dim::Known(n)) => stride *= *n as u64,
                            _ => {
                                return Err(Error::UnsupportedOp(format!(
                                    "cuda: multi-dim index needs static dims on `{src}`"
                                )));
                            },
                        }
                    }
                    terms.push(format!("({}) * {stride}u", self.idx_term(ix, block, ov)));
                }
                Ok(terms.join(" + "))
            },
        }
    }

    fn idx_term(&self, ix: &IndexExpr, block: &Block, ov: &Names) -> String {
        match ix {
            IndexExpr::Value(v) => self.vname(Some(*v), block, ov),
            IndexExpr::Const(c) => c.to_string(),
            IndexExpr::Range(v, off) => format!("({} + {off})", self.vname(Some(*v), block, ov)),
        }
    }

    // ── Kernel signature ───────────────────────────────────────────────
    fn emit_signature(&self, kernel: &Kernel, out: &mut String) -> Result<()> {
        writeln!(out, "extern \"C\" __global__ void {}(", kernel.name).ok();
        let mut args: Vec<String> = Vec::new();
        for p in &kernel.params {
            args.push(self.emit_param(p)?);
        }
        for ce in &kernel.constexprs {
            // Scalars are passed by value as kernel arguments.
            args.push(format!("    {} {}", cuda_type_name(ce.dtype), ce.name.name()));
        }
        // Elementwise kernels carry a synthetic element-count for the bounds
        // guard. Reduction kernels are bounded per-row by the strided loop's
        // `end`, so they need no such param.
        if kernel.mode == KernelMode::Elementwise {
            args.push(format!("    unsigned int {N_ELEMS_PARAM}"));
        }
        writeln!(out, "{}", args.join(",\n")).ok();
        writeln!(out, ") {{").ok();
        Ok(())
    }

    fn emit_param(&self, p: &Param) -> Result<String> {
        match p.kind {
            ParamKind::Tensor => {
                let ty = cuda_type_name(p.dtype);
                // __restrict__: input tensors don't alias each other or the outputs,
                // enabling the compiler to issue LDG.128 (L1 read-only cache) and
                // schedule loads more aggressively. Output tensors are also
                // __restrict__ since we never alias an output with an input.
                Ok(if p.is_output {
                    format!("    {ty}* __restrict__ {}", p.name)
                } else {
                    format!("    const {ty}* __restrict__ {}", p.name)
                })
            },
            ParamKind::Scalar => Ok(format!("    {} {}", cuda_type_name(p.dtype), p.name)),
            // Strided tensor: data ptr + companion shape/strides buffers
            // (referenced in the IR via Load{src:"{name}_shape"/"_strides"}).
            ParamKind::Strided => {
                let ty = cuda_type_name(p.dtype);
                let q = if p.is_output { "" } else { "const " };
                Ok(format!(
                    "    {q}{ty}* __restrict__ {0},\n    const unsigned int* __restrict__ {0}_shape,\n    const unsigned int* __restrict__ {0}_strides",
                    p.name
                ))
            },
        }
    }

    // ── Body ───────────────────────────────────────────────────────────
    fn emit_body(&self, kernel: &Kernel, out: &mut String) -> Result<()> {
        match kernel.mode {
            KernelMode::Elementwise => {
                // Global linear thread id + bounds guard.
                writeln!(
                    out,
                    "    const unsigned int _gtid = blockIdx.x * blockDim.x + threadIdx.x;"
                )
                .ok();
                writeln!(out, "    if (_gtid >= {N_ELEMS_PARAM}) return;").ok();
                // `tid` alias: the DSL's `tid` lowers to Load{src:"tid"}; in
                // Elementwise mode it is the global linear index.
                writeln!(out, "    const unsigned int tid = _gtid;").ok();
                self.emit_simd_aliases(out);
            },
            KernelMode::Reduction => {
                // The `n_simd==0 → return` freeze guard is only for the
                // threadgroup-reduce tree (needs ≥32 threads). Kernels that
                // don't `Reduce` (e.g. hadamard_m, tpg=12/20/28) must NOT
                // return — gate the guard on Op::Reduce presence.
                let needs_guard = kernel_has_reduce(kernel);
                self.emit_reduction_preamble(out, needs_guard);
            },
            KernelMode::Grid3D => {
                // 3-axis global thread id; ProgramId(axis) → gid_{x,y,z}.
                // Same launch geometry as Metal's dispatchThreadgroups, so
                // no extra bounds guard is needed (parity with Metal).
                writeln!(
                    out,
                    "    const unsigned int gid_x = blockIdx.x * blockDim.x + threadIdx.x;"
                )
                .ok();
                writeln!(
                    out,
                    "    const unsigned int gid_y = blockIdx.y * blockDim.y + threadIdx.y;"
                )
                .ok();
                writeln!(
                    out,
                    "    const unsigned int gid_z = blockIdx.z * blockDim.z + threadIdx.z;"
                )
                .ok();
                self.emit_simd_aliases(out);
            },
            KernelMode::SimdGroup2D => {
                // tid = threadgroup_position_in_grid (→ blockIdx),
                // lid = thread_position_in_threadgroup (→ threadIdx).
                writeln!(out, "    const unsigned int tgid_x = blockIdx.x;").ok();
                writeln!(out, "    const unsigned int tgid_y = blockIdx.y;").ok();
                writeln!(out, "    const unsigned int tgid_z = blockIdx.z;").ok();
                writeln!(out, "    const unsigned int lid_x = threadIdx.x;").ok();
                writeln!(out, "    const unsigned int lid_y = threadIdx.y;").ok();
                writeln!(out, "    const unsigned int lid_z = threadIdx.z;").ok();
                self.emit_simd_aliases(out);
            },
            KernelMode::Tile2D => {
                return Err(Error::UnsupportedOp(
                    "cuda: KernelMode Tile2D (Op::Dot tiled-matmul path → wmma, Phase 3)".into(),
                ));
            },
        }

        // Apple simdgroup_matrix<f32,8,8> lane→element coords (from the
        // mma_layout_probe): elem 0 at (fm, fn0), elem 1 at (fm, fn1).
        if uses_simdgroup(kernel) {
            writeln!(out, "    const unsigned int _sg_qid = simd_lane / 4u;").ok();
            writeln!(
                out,
                "    const unsigned int _sg_fm  = (_sg_qid & 4u) + ((simd_lane / 2u) % 4u);"
            )
            .ok();
            writeln!(
                out,
                "    const unsigned int _sg_fn0 = (_sg_qid & 2u) * 2u + (simd_lane % 2u) * 2u;"
            )
            .ok();
            writeln!(out, "    const unsigned int _sg_fn1 = _sg_fn0 + 1u;").ok();
        }

        // Hoist threadgroup/stack array declarations to function scope so
        // they're visible across nested Loop/If blocks (mirrors MSL hoists).
        self.emit_allocs(kernel, out);
        self.emit_ops(&kernel.body, kernel, &Names::new(), out)?;
        writeln!(out, "}}").ok();
        Ok(())
    }

    /// Emit `__shared__` (ThreadgroupAlloc) and per-thread array (StackAlloc)
    /// declarations from every block, at function scope.
    fn emit_allocs(&self, kernel: &Kernel, out: &mut String) {
        // Per-thread local arrays (registers/local mem), not shared.
        for blk in std::iter::once(&kernel.body).chain(kernel.blocks.values()) {
            for op in &blk.ops {
                if let Op::StackAlloc { dtype, size, name } = op {
                    writeln!(out, "    {} {name}[{size}];", cuda_type_name(*dtype)).ok();
                }
            }
        }
        // SoftwareLocalC: each unique SimdGroup-scope CoopTile C-group
        // gets a lane-local VGPR array of size `m*n / lane_width`. Each
        // lane holds its own slice; the cooperative iteration that used
        // to walk `simd_lane, simd_lane+32, …` of a shared array now
        // walks a plain 0..m*n/lane_width loop over this private array.
        if matches!(self.profile.mma, crate::backend::MmaStrategy::SoftwareLocalC) {
            let lw = self.profile.lane_width;
            let mut seen_c: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
            for blk in std::iter::once(&kernel.body).chain(kernel.blocks.values()) {
                for op in &blk.ops {
                    if let Op::CoopTileSetup { name, m, n, exec_scope, .. } = op
                        && matches!(exec_scope, CoopTileScope::SimdGroup)
                    {
                        let cnm = ct_ident(&coop_c_name(name));
                        if seen_c.insert(cnm.clone()) {
                            let per_lane = (m * n).div_ceil(lw).max(1);
                            writeln!(out, "    float _CTC_lane_{cnm}[{per_lane}];").ok();
                        }
                    }
                }
            }
        }
        // Shared arrays go in DYNAMIC shared memory, sized at runtime to the
        // actual warp count (`_nw`) — avoids the 48KB static cap and the
        // 32-warp over-allocation. Per-warp arrays (simdgroup tiles) are
        // packed `_nw × per_warp`; threadgroup-scope arrays are sized once.
        // The runtime sets cuFuncAttributeMaxDynamicSharedSize + passes the
        // matching byte count (see `shared_bytes`).
        let arrays = self.shared_arrays(kernel);
        if arrays.is_empty() {
            return;
        }
        writeln!(out, "    extern __shared__ unsigned char _smem[];").ok();
        writeln!(
            out,
            "    const unsigned int _nw = (blockDim.x * blockDim.y * blockDim.z + 31u) / 32u;"
        )
        .ok();
        writeln!(out, "    unsigned int _so = 0u;").ok();
        for (name, ctype, count, per_warp, bytes) in &arrays {
            let wf = if *per_warp { "_nw" } else { "1u" };
            // Align each array's base to its element size — a preceding
            // odd-length half/byte tile must not misalign this one. MUST stay
            // in lockstep with the identical rounding in `shared_bytes`.
            if *bytes > 1 {
                let m = bytes - 1;
                writeln!(out, "    _so = (_so + {m}u) & ~{m}u;").ok();
            }
            writeln!(out, "    {ctype}* {name} = ({ctype}*)(_smem + _so);").ok();
            writeln!(out, "    _so += {wf} * {count}u * sizeof({ctype});").ok();
        }
        writeln!(out, "    (void)_so;").ok();
    }

    /// The ordered shared-memory layout: (name, C type, element count,
    /// per-warp?, element bytes). Drives both `emit_allocs` (pointer setup)
    /// and `shared_bytes` (runtime size). Order MUST match between the two.
    ///
    /// With `MmaStrategy::SoftwareLocalC` (HIP wave32 / wave64), the per-
    /// warp CoopTile **C** accumulator is omitted here — it moves to a
    /// lane-local VGPR array declared in `emit_allocs`. Saves
    /// `nw * m*n * 4` bytes of shared LDS, which is exactly the headroom
    /// MPP `bm64` kernels need to fit under RDNA 4's 64 KB cap.
    fn shared_arrays(&self, kernel: &Kernel) -> Vec<(String, &'static str, u32, bool, usize)> {
        let mut v = Vec::new();
        let mut seen_c: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
        let local_c = matches!(self.profile.mma, crate::backend::MmaStrategy::SoftwareLocalC);
        for blk in std::iter::once(&kernel.body).chain(kernel.blocks.values()) {
            for (i, op) in blk.ops.iter().enumerate() {
                match op {
                    Op::ThreadgroupAlloc { dtype, size, name } => {
                        v.push((
                            name.clone(),
                            cuda_type_name(*dtype),
                            *size,
                            false,
                            dtype.size_bytes(),
                        ));
                    },
                    Op::SimdgroupAlloc { .. } =>
                        if let Some(Some(vid)) = blk.results.get(i) {
                            v.push((sgm_name(*vid), "float", 64, true, 4));
                        },
                    Op::CoopTileSetup { name, m, n, k, exec_scope, .. } => {
                        let pw = matches!(exec_scope, CoopTileScope::SimdGroup);
                        let nm = ct_ident(name);
                        v.push((format!("_CTA_{nm}"), "float", m * k, pw, 4));
                        v.push((format!("_CTB_{nm}"), "float", k * n, pw, 4));
                        // C is the persistent accumulator: an `*_acc`
                        // (multiply-accumulate) setup SHARES its C with the
                        // base setup (e.g. qk_acc accumulates onto qk's C),
                        // so the C tile is declared once per c-group.
                        let cnm = ct_ident(&coop_c_name(name));
                        if seen_c.insert(cnm.clone()) {
                            // SoftwareLocalC: SimdGroup-scope C lives in
                            // VGPRs (see emit_allocs); skip the shared
                            // entry. Threadgroup-scope C still uses shared.
                            let skip = local_c && pw;
                            if !skip {
                                v.push((format!("_CTC_{cnm}"), "float", m * n, pw, 4));
                            }
                        }
                    },
                    _ => {},
                }
            }
        }
        v
    }

    /// Total dynamic shared-memory bytes for a launch of `block_threads`
    /// total threads (x·y·z). Walks the same array order as `emit_allocs`
    /// and applies the same per-array element-size alignment — the two MUST
    /// stay in lockstep or the runtime under/over-sizes the launch.
    pub fn shared_bytes(&self, kernel: &Kernel, block_threads: u32) -> usize {
        let nw = block_threads.div_ceil(32).max(1) as usize;
        let mut total = 0usize;
        for (_, _, count, per_warp, bytes) in self.shared_arrays(kernel) {
            if bytes > 1 {
                total = total.next_multiple_of(bytes);
            }
            total += (if per_warp { nw } else { 1 }) * count as usize * bytes;
        }
        total
    }

    /// Walk a block's ops, emitting each. `ov` carries name overrides from
    /// any enclosing Loop/If scope.
    fn emit_ops(&self, blk: &Block, kernel: &Kernel, ov: &Names, out: &mut String) -> Result<()> {
        for (i, op) in blk.ops.iter().enumerate() {
            let vid = blk.results.get(i).and_then(|x| *x);
            self.emit_op(op, vid, blk, kernel, ov, out)?;
        }
        Ok(())
    }

    /// Build the override map for a nested block: the parent block's name
    /// hints (as `v_<hint>`) plus the parent's own overrides — mirrors
    /// MSL's `child_names` so SSA values defined in the parent are visible
    /// inside the child.
    fn child_ov(&self, parent: &Block, ov: &Names) -> Names {
        let mut child: Names =
            parent.names.iter().map(|(&k, v)| (k, format!("v_{v}_{}", k.as_u32()))).collect();
        for (&k, v) in ov {
            child.insert(k, v.clone());
        }
        child
    }

    /// Common threadgroup/warp aliases available in every mode (kernels
    /// reference `lsize`/`simd_lane`/`simd_group`/`n_simd` regardless of
    /// thread-index mode). Reduction defines these in its own preamble, so
    /// this is only called for Elementwise/Grid3D.
    fn emit_simd_aliases(&self, out: &mut String) {
        let lw = self.profile.lane_width;
        // Lane/warp ids derive from the FLATTENED in-block thread index —
        // hardware warps are carved from the linearised (z,y,x) order, so
        // threadIdx.x alone is wrong whenever blockDim.y/z > 1.
        writeln!(out, "    const unsigned int _ltid      = (threadIdx.z * blockDim.y + threadIdx.y) * blockDim.x + threadIdx.x;").ok();
        writeln!(out, "    const unsigned int lsize      = blockDim.x * blockDim.y * blockDim.z;")
            .ok();
        writeln!(out, "    const unsigned int n_simd     = lsize / {lw}u;").ok();
        writeln!(out, "    const unsigned int simd_lane  = _ltid % {lw}u;").ok();
        writeln!(out, "    const unsigned int simd_group = _ltid / {lw}u;").ok();
    }

    /// Reduction-mode preamble: maps Metal's threadgroup/simd built-ins to
    /// CUDA. Block-per-output-row; warp = 32-lane (the lucky match). The
    /// `n_simd == 0` guard mirrors the Metal freeze-hazard guard (harmless
    /// on CUDA, kept for parity).
    fn emit_reduction_preamble(&self, out: &mut String, needs_guard: bool) {
        let lw = self.profile.lane_width;
        // `tid`/lane/warp ids derive from the FLATTENED in-block thread index
        // (hardware warps follow the linearised (z,y,x) order); threadIdx.x
        // alone is wrong whenever blockDim.y/z > 1.
        writeln!(out, "    const unsigned int _ltid     = (threadIdx.z * blockDim.y + threadIdx.y) * blockDim.x + threadIdx.x;").ok();
        writeln!(out, "    const unsigned int tid       = _ltid;").ok();
        writeln!(out, "    const unsigned int tgid_x    = blockIdx.x;").ok();
        writeln!(out, "    const unsigned int tgid_y    = blockIdx.y;").ok();
        writeln!(out, "    const unsigned int tgid_z    = blockIdx.z;").ok();
        writeln!(out, "    const unsigned int lsize     = blockDim.x * blockDim.y * blockDim.z;")
            .ok();
        writeln!(out, "    const unsigned int n_simd    = lsize / {lw}u;").ok();
        if needs_guard {
            // Only the threadgroup-reduce tree needs ≥32 threads; sub-warp
            // kernels without a Reduce (hadamard_m) must keep running.
            writeln!(out, "    if (n_simd == 0u) return;").ok();
        }
        writeln!(out, "    const unsigned int simd_lane  = _ltid % {lw}u;").ok();
        writeln!(out, "    const unsigned int simd_group = _ltid / {lw}u;").ok();
    }

    fn emit_op(
        &self,
        op: &Op,
        vid: Option<ValueId>,
        block: &Block,
        kernel: &Kernel,
        ov: &Names,
        out: &mut String,
    ) -> Result<()> {
        let pad = "    ";
        match op {
            Op::ProgramId { axis } => {
                let v = self.vname(vid, block, ov);
                let src = match kernel.mode {
                    // Elementwise: the single linear thread id.
                    KernelMode::Elementwise => "_gtid".to_string(),
                    // Grid3D: per-axis global thread id.
                    KernelMode::Grid3D => match axis {
                        0 => "gid_x",
                        1 => "gid_y",
                        _ => "gid_z",
                    }
                    .to_string(),
                    // Reduction & SimdGroup2D: which threadgroup (block) this is.
                    _ => match axis {
                        0 => "tgid_x",
                        1 => "tgid_y",
                        _ => "tgid_z",
                    }
                    .to_string(),
                };
                writeln!(out, "{pad}unsigned int {v} = {src};").ok();
            },
            Op::Const { value } => {
                let v = self.vname(vid, block, ov);
                if *value >= 0 {
                    writeln!(out, "{pad}unsigned int {v} = {value}u;").ok();
                } else {
                    writeln!(out, "{pad}int {v} = {value};").ok();
                }
            },
            Op::Load { src, indices, .. } => {
                let v = self.vname(vid, block, ov);
                // DSL builtin aliases. `simd_id` → warp index. In SimdGroup2D,
                // `tid_{x,y,z}` is the per-thread position (lid) — matches MSL.
                let src = match (src.as_str(), kernel.mode) {
                    ("simd_id", _) => "simd_group",
                    ("tid_x", KernelMode::SimdGroup2D) => "lid_x",
                    ("tid_y", KernelMode::SimdGroup2D) => "lid_y",
                    ("tid_z", KernelMode::SimdGroup2D) => "lid_z",
                    _ => src.as_str(),
                };
                if indices.is_empty() {
                    writeln!(out, "{pad}auto {v} = {src};").ok();
                } else {
                    let idx = self.emit_idx(indices, block, ov, kernel, src)?;
                    // Use __ldg() for read-only tensor loads: routes through the
                    // L1 read-only (texture) cache, bypasses L1 unified cache,
                    // and enables the compiler to issue LDG.128 / LDG.64 for
                    // coalesced accesses. Requires __restrict__ on the parameter
                    // (added in emit_param). Only apply to Tensor params (not
                    // builtins like simd_id, tid_x, …).
                    let ro_param = kernel
                        .params
                        .iter()
                        .find(|p| p.name == *src && p.kind == ParamKind::Tensor && !p.is_output);
                    if let Some(p) = ro_param {
                        // Cache-streaming (`__ldcs`, `.cs` hint) for the BIG read-
                        // ONCE Q4 weights (always U32-packed): they're streamed
                        // through exactly once per token, so the default cache-all
                        // (`__ldg`) just pollutes L2 — evicting reused activations.
                        // `.cs` marks the line evict-first so the weight stream
                        // doesn't thrash L2. Gated by IRON_LDCS_WEIGHTS (default off);
                        // activations/scales (T/f16) stay __ldg (reused across lanes).
                        let ldcs =
                            p.dtype == DType::U32 && std::env::var("IRON_LDCS_WEIGHTS").is_ok();
                        if ldcs {
                            writeln!(out, "{pad}auto {v} = __ldcs(&{src}[{idx}]);").ok();
                        } else {
                            writeln!(out, "{pad}auto {v} = __ldg(&{src}[{idx}]);").ok();
                        }
                    } else {
                        writeln!(out, "{pad}auto {v} = {src}[{idx}];").ok();
                    }
                }
            },
            Op::Store { dst, indices, value, .. } => {
                let val = self.vname(Some(*value), block, ov);
                let idx = self.emit_idx(indices, block, ov, kernel, dst)?;
                writeln!(out, "{pad}{dst}[{idx}] = {val};").ok();
            },
            Op::BinOp { op: bop, lhs, rhs } => {
                let v = self.vname(vid, block, ov);
                let l = self.vname(Some(*lhs), block, ov);
                let r = self.vname(Some(*rhs), block, ov);
                // Route divide through Markstein-refined helper when the
                // profile asks for it (HIP — closes the gated-DeltaNet
                // KNOWN_HARD; CUDA default stays on `a / b`). Integer
                // overloads of `iron_fdiv` pass through to `/`, so the
                // emit must NOT cast operands to float — that would lose
                // `int / int = int` index math.
                if matches!(bop, BinOpKind::Div) && self.profile.precise_simd_sum {
                    writeln!(out, "{pad}auto {v} = iron_fdiv({l}, {r});").ok();
                } else {
                    writeln!(out, "{pad}auto {v} = {};", cuda_binop(*bop, &l, &r)).ok();
                }
            },
            Op::Fma { a, b, c } => {
                let v = self.vname(vid, block, ov);
                let av = self.vname(Some(*a), block, ov);
                let bv = self.vname(Some(*b), block, ov);
                let cv = self.vname(Some(*c), block, ov);
                writeln!(out, "{pad}auto {v} = fmaf({av}, {bv}, {cv});").ok();
            },
            Op::UnaryOp { op: uop, value } => {
                let v = self.vname(vid, block, ov);
                let rv = self.vname(Some(*value), block, ov);
                writeln!(out, "{pad}auto {v} = {};", self.cuda_unary(*uop, &rv)).ok();
            },
            Op::Cast { value, dtype } => {
                let v = self.vname(vid, block, ov);
                let rv = self.vname(Some(*value), block, ov);
                let ty = cuda_type_name(*dtype);
                // CUDA C-style cast; source type comes from `auto` inference.
                writeln!(out, "{pad}{ty} {v} = ({ty})({rv});").ok();
            },
            Op::Select { cond, on_true, on_false } => {
                let v = self.vname(vid, block, ov);
                let c = self.vname(Some(*cond), block, ov);
                let a = self.vname(Some(*on_true), block, ov);
                let b = self.vname(Some(*on_false), block, ov);
                writeln!(out, "{pad}auto {v} = ({c}) ? ({a}) : ({b});").ok();
            },
            // Mutable locals: the macro lowers `let mut x` to DeclareLocal and
            // reads to Load{src:"__ml_x"} (body.rs), so the names line up.
            Op::DeclareLocal { name, value } => {
                let rv = self.vname(Some(*value), block, ov);
                writeln!(out, "{pad}auto __ml_{name} = {rv};").ok();
            },
            Op::SetLocal { name, value } => {
                let rv = self.vname(Some(*value), block, ov);
                writeln!(out, "{pad}__ml_{name} = {rv};").ok();
            },
            Op::Activation { kind, value } => {
                let v = self.vname(vid, block, ov);
                let rv = self.vname(Some(*value), block, ov);
                let expr = match kind {
                    ActKind::Silu => format!("iron_silu((float)({rv}))"),
                    ActKind::Gelu => format!("iron_gelu((float)({rv}))"),
                    ActKind::Relu => format!("iron_relu((float)({rv}))"),
                    ActKind::Sigmoid => format!("iron_sigmoid((float)({rv}))"),
                    ActKind::Tanh => format!("tanhf((float)({rv}))"),
                };
                writeln!(out, "{pad}auto {v} = {expr};").ok();
            },
            // Single-warp SIMD reduction → xor butterfly so ALL lanes get
            // the result (matches Metal `simd_*` broadcast semantics).
            //
            // When the profile sets `precise_simd_sum`, f32 Sum/Mean drop
            // the butterfly tree (5 ops on wave32, 6 on wave64) for a
            // linear-order shuffle accumulator (lane_width ops) so the
            // GPU result rounds the same way Rust's `iter().sum()` does
            // left-to-right. HIP turns this on to close the gated-DeltaNet
            // KNOWN_HARD; CUDA keeps the fast butterfly path.
            Op::SimdReduce { value, op: rk } => {
                let v = self.vname(vid, block, ov);
                let rv = self.vname(Some(*value), block, ov);
                let lw = self.profile.lane_width;
                let is_sum = matches!(rk, ReduceKind::Sum | ReduceKind::Mean);
                if self.profile.precise_simd_sum && is_sum {
                    writeln!(out, "{pad}float {v};").ok();
                    writeln!(out, "{pad}{{").ok();
                    writeln!(out, "{pad}    float _src = (float)({rv});").ok();
                    // `volatile` forces left-to-right materialization —
                    // without it the AMDGPU optimizer can reassociate the
                    // 32-step accumulator into a balanced tree (a
                    // different rounding path than the CPU oracle uses).
                    writeln!(out, "{pad}    volatile float _s = 0.0f;").ok();
                    writeln!(out, "{pad}    for (int _i = 0; _i < {lw}; _i++) {{").ok();
                    writeln!(out, "{pad}        _s = _s + __shfl_sync(0xffffffffu, _src, _i);")
                        .ok();
                    writeln!(out, "{pad}    }}").ok();
                    if *rk == ReduceKind::Mean {
                        writeln!(out, "{pad}    {v} = _s / {lw}.0f;").ok();
                    } else {
                        writeln!(out, "{pad}    {v} = _s;").ok();
                    }
                    writeln!(out, "{pad}}}").ok();
                } else {
                    let half = lw / 2;
                    writeln!(out, "{pad}float {v};").ok();
                    writeln!(out, "{pad}{{").ok();
                    writeln!(out, "{pad}    float _s = (float)({rv});").ok();
                    writeln!(out, "{pad}    for (int _o = {half}; _o > 0; _o >>= 1) {{").ok();
                    writeln!(out, "{pad}        float _x = __shfl_xor_sync(0xffffffffu, _s, _o);")
                        .ok();
                    writeln!(out, "{pad}        _s = {};", reduce_combine(*rk, "_s", "_x")).ok();
                    writeln!(out, "{pad}    }}").ok();
                    if *rk == ReduceKind::Mean {
                        writeln!(out, "{pad}    {v} = _s / {lw}.0f;").ok();
                    } else {
                        writeln!(out, "{pad}    {v} = _s;").ok();
                    }
                    writeln!(out, "{pad}}}").ok();
                }
            },
            // Warp prefix scan (Hillis-Steele via __shfl_up_sync), matching
            // Metal's simd_prefix_{inclusive,exclusive}_*.
            Op::SimdScan { value, op: rk, exclusive } => {
                let v = self.vname(vid, block, ov);
                let rv = self.vname(Some(*value), block, ov);
                let lw = self.profile.lane_width;
                writeln!(out, "{pad}float {v};").ok();
                writeln!(out, "{pad}{{").ok();
                writeln!(out, "{pad}    float _s = (float)({rv});").ok();
                writeln!(out, "{pad}    for (int _o = 1; _o < {lw}; _o <<= 1) {{").ok();
                writeln!(out, "{pad}        float _t = __shfl_up_sync(0xffffffffu, _s, _o);").ok();
                writeln!(
                    out,
                    "{pad}        if (simd_lane >= (unsigned int)_o) _s = {};",
                    reduce_combine(*rk, "_s", "_t")
                )
                .ok();
                writeln!(out, "{pad}    }}").ok();
                if *exclusive {
                    // Shift right one lane; lane 0 gets the identity.
                    writeln!(out, "{pad}    float _x = __shfl_up_sync(0xffffffffu, _s, 1);").ok();
                    writeln!(
                        out,
                        "{pad}    {v} = (simd_lane == 0u) ? ({}) : _x;",
                        reduce_init(*rk)
                    )
                    .ok();
                } else {
                    writeln!(out, "{pad}    {v} = _s;").ok();
                }
                writeln!(out, "{pad}}}").ok();
            },
            // Scalar (rank-0) splat / zeros. Tile (array) shapes need the
            // threadgroup/stack allocation path (cooperative kernels, P3+).
            Op::Zeros { shape, .. } if shape.rank() == 0 => {
                let v = self.vname(vid, block, ov);
                writeln!(out, "{pad}float {v} = 0.0f;").ok();
            },
            Op::Splat { value, shape, .. } if shape.rank() == 0 => {
                let v = self.vname(vid, block, ov);
                writeln!(out, "{pad}float {v} = {};", fmt_f32_lit(*value)).ok();
            },
            // Per-thread grid-stride accumulation over a row (Phase 2).
            // Each thread sums src[offset+tid], src[offset+tid+lsize], …
            // Correctness-first: the 4-wide vectorized form the MSL path uses
            // is a Phase-3 perf retune (SCOPE §6).
            Op::StrideReduce {
                src,
                offset,
                stride,
                end,
                op: rk,
                transform,
                secondary_src,
                secondary_base,
                ..
            } => {
                let v = self.vname(vid, block, ov);
                let off = self.vname(Some(*offset), block, ov);
                let en = self.vname(Some(*end), block, ov);
                // Two layouts:
                //  - Reduction/Tile2D: the threadgroup *cooperates* over one
                //    row — each thread strides by `lsize`, a later Op::Reduce
                //    combines (start at off+tid).
                //  - Grid3D/Elementwise: each thread folds its OWN run
                //    (col-reduce: stride=cols; seg-reduce: stride=1) with no
                //    threadgroup combine — start at `off`, step by `stride`.
                let coop = matches!(kernel.mode, KernelMode::Reduction | KernelMode::Tile2D);
                let (start, step) = if coop {
                    (format!("{off} + tid"), "lsize".to_string())
                } else {
                    (off.clone(), self.vname(Some(*stride), block, ov))
                };
                // Base element: optional dot-product against a second buffer
                // (GEMV/qgemv: src[_i] * sec[_i - base]).
                let base_elem = match secondary_src {
                    Some(sec) => {
                        let bv = self.vname(*secondary_base, block, ov);
                        format!("(float)({src}[_i]) * (float)({sec}[_i - {bv}])")
                    },
                    None => format!("(float)({src}[_i])"),
                };
                // Per-element transform chain (e.g. square for sum-of-squares,
                // decode, activation), applied to the loaded element.
                let elem_expr = match transform.as_ref().map(|t| t.as_slice()) {
                    None | Some([]) => base_elem,
                    Some(ops) => {
                        let mut e = base_elem;
                        for sub in ops {
                            e = match sub {
                                Op::UnaryOp { op, .. } => self.cuda_unary(*op, &e),
                                Op::Activation { kind, .. } => match kind {
                                    ActKind::Silu => format!("iron_silu({e})"),
                                    ActKind::Gelu => format!("iron_gelu({e})"),
                                    ActKind::Relu => format!("iron_relu({e})"),
                                    ActKind::Sigmoid => format!("iron_sigmoid({e})"),
                                    ActKind::Tanh => format!("tanhf({e})"),
                                },
                                Op::Cast { dtype, .. } => {
                                    format!("({})({e})", cuda_type_name(*dtype))
                                },
                                Op::BinOp { op, rhs, .. } => {
                                    let rv = self.vname(Some(*rhs), block, ov);
                                    match op {
                                        BinOpKind::Mul => format!("(({e}) * (float)({rv}))"),
                                        BinOpKind::Add => format!("(({e}) + (float)({rv}))"),
                                        BinOpKind::Sub => format!("(({e}) - (float)({rv}))"),
                                        BinOpKind::Div => format!("(({e}) / (float)({rv}))"),
                                        _ => e,
                                    }
                                },
                                _ => e,
                            };
                        }
                        e
                    },
                };
                writeln!(out, "{pad}float {v} = {};", reduce_init(*rk)).ok();
                writeln!(out, "{pad}for (unsigned int _i = {start}; _i < {en}; _i += {step}) {{")
                    .ok();
                writeln!(out, "{pad}    float _e = {elem_expr};").ok();
                writeln!(out, "{pad}    {v} = {};", reduce_combine(*rk, &v, "_e")).ok();
                writeln!(out, "{pad}}}").ok();
            },
            // Threadgroup-scope reduction: warp shuffle + shared-mem tree
            // (the CUDA analog of msl::reduce two-level simd_sum). Phase 2.
            Op::Reduce { value, axis, op: rk } => {
                if *axis != 0 {
                    return Err(Error::UnsupportedOp(
                        "cuda Phase 2: Reduce axis != 0 (Phase 3)".into(),
                    ));
                }
                let v = self.vname(vid, block, ov);
                let input = self.vname(Some(*value), block, ov);
                self.emit_reduce_tree(&v, &input, *rk, out);
            },
            // ── Threadgroup / warp primitives (non-MMA) ────────────────
            // Allocs are hoisted by emit_allocs; the ops themselves are no-ops.
            Op::ThreadgroupAlloc { .. } | Op::StackAlloc { .. } => {},
            Op::ThreadgroupLoad { name, index } | Op::StackLoad { name, index } => {
                let v = self.vname(vid, block, ov);
                let iv = self.vname(Some(*index), block, ov);
                writeln!(out, "{pad}auto {v} = {name}[{iv}];").ok();
            },
            Op::ThreadgroupStore { name, index, value } | Op::StackStore { name, index, value } => {
                let iv = self.vname(Some(*index), block, ov);
                let rv = self.vname(Some(*value), block, ov);
                writeln!(out, "{pad}{name}[{iv}] = {rv};").ok();
            },
            Op::SimdLaneId => {
                let v = self.vname(vid, block, ov);
                writeln!(out, "{pad}unsigned int {v} = simd_lane;").ok();
            },
            Op::SimdGroupId => {
                let v = self.vname(vid, block, ov);
                writeln!(out, "{pad}unsigned int {v} = simd_group;").ok();
            },
            Op::SimdBroadcast { value, lane } => {
                let v = self.vname(vid, block, ov);
                let rv = self.vname(Some(*value), block, ov);
                let rl = self.vname(Some(*lane), block, ov);
                writeln!(out, "{pad}auto {v} = __shfl_sync(0xffffffffu, {rv}, {rl});").ok();
            },
            Op::SimdShuffleXor { value, mask } => {
                let v = self.vname(vid, block, ov);
                let rv = self.vname(Some(*value), block, ov);
                writeln!(out, "{pad}auto {v} = __shfl_xor_sync(0xffffffffu, {rv}, {mask}u);").ok();
            },
            Op::Barrier => {
                writeln!(out, "{pad}__syncthreads();").ok();
            },
            Op::Atomic { op: ak, dst, index, value, .. } => {
                let iv = self.vname(Some(*index), block, ov);
                let rv = self.vname(Some(*value), block, ov);
                let f = match ak {
                    AtomicKind::Add => "atomicAdd",
                    AtomicKind::Max => "atomicMax",
                    AtomicKind::Min => "atomicMin",
                    AtomicKind::And => "atomicAnd",
                    AtomicKind::Or => "atomicOr",
                    AtomicKind::Xor => "atomicXor",
                };
                writeln!(out, "{pad}{f}(&{dst}[{iv}], {rv});").ok();
            },
            Op::SimdgroupBarrier => {
                writeln!(out, "{pad}__syncwarp();").ok();
            },
            // ── simdgroup_matrix<f32,8,8> (software emulation) ─────────
            // Each fragment is a per-warp 8×8 row-major shared tile; lanes
            // map to elements via the Apple layout (_sg_fm/_sg_fn0/_sg_fn1).
            // Cooperative across the 32-lane warp = 32-lane simdgroup.
            Op::SimdgroupAlloc { .. } => {}, // declared+zeroed in emit_allocs
            Op::SimdgroupElemLoad { value, index } => {
                let v = self.vname(vid, block, ov);
                let m = sgm_name(*value);
                let fnk = if *index == 0 { "_sg_fn0" } else { "_sg_fn1" };
                writeln!(out, "{pad}float {v} = {m}[simd_group * 64u + _sg_fm * 8u + {fnk}];").ok();
            },
            Op::SimdgroupElemStore { value, index, data } => {
                let m = sgm_name(*value);
                let dv = self.vname(Some(*data), block, ov);
                let fnk = if *index == 0 { "_sg_fn0" } else { "_sg_fn1" };
                writeln!(out, "{pad}{m}[simd_group * 64u + _sg_fm * 8u + {fnk}] = {dv};").ok();
            },
            // Cooperative fragment load from a threadgroup array, one row per
            // (fm,fn): dest[fm][fn] = tg[off + (transpose ? fn*stride+fm : fm*stride+fn)].
            Op::SimdgroupLoad { dest, tg, offset, stride, transpose } => {
                let m = sgm_name(*dest);
                let off = self.vname(Some(*offset), block, ov);
                writeln!(out, "{pad}{{ unsigned int _base = simd_group * 64u;").ok();
                for fnk in ["_sg_fn0", "_sg_fn1"] {
                    let idx = if *transpose {
                        format!("{fnk} * {stride}u + _sg_fm")
                    } else {
                        format!("_sg_fm * {stride}u + {fnk}")
                    };
                    writeln!(
                        out,
                        "{pad}    {m}[_base + _sg_fm * 8u + {fnk}] = (float)({tg}[{off} + {idx}]);"
                    )
                    .ok();
                }
                writeln!(out, "{pad}}}").ok();
            },
            // C += A * B  (8×8×8), cooperative across the warp.
            Op::SimdgroupMatMul { a, b, c } => {
                let (ma, mb, mc) = (sgm_name(*a), sgm_name(*b), sgm_name(*c));
                writeln!(out, "{pad}__syncwarp();").ok();
                writeln!(out, "{pad}{{ unsigned int _bs = simd_group * 64u;").ok();
                writeln!(out, "{pad}    float _acc0 = {mc}[_bs + _sg_fm * 8u + _sg_fn0];").ok();
                writeln!(out, "{pad}    float _acc1 = {mc}[_bs + _sg_fm * 8u + _sg_fn1];").ok();
                writeln!(out, "{pad}    for (unsigned int _k = 0u; _k < 8u; _k++) {{").ok();
                writeln!(out, "{pad}        float _av = {ma}[_bs + _sg_fm * 8u + _k];").ok();
                writeln!(out, "{pad}        _acc0 += _av * {mb}[_bs + _k * 8u + _sg_fn0];").ok();
                writeln!(out, "{pad}        _acc1 += _av * {mb}[_bs + _k * 8u + _sg_fn1];").ok();
                writeln!(out, "{pad}    }}").ok();
                writeln!(out, "{pad}    __syncwarp();").ok();
                writeln!(out, "{pad}    {mc}[_bs + _sg_fm * 8u + _sg_fn0] = _acc0;").ok();
                writeln!(out, "{pad}    {mc}[_bs + _sg_fm * 8u + _sg_fn1] = _acc1;").ok();
                writeln!(out, "{pad}}}").ok();
            },
            // ── CoopTile cooperative GEMM (MPP/NAX → software emulation) ──
            // Opaque tiles (Load→Run→Store, no element access) → staged in
            // shared memory with a self-consistent row-major layout. C
            // persists across K-block Run calls (accumulate mode).
            Op::CoopTileSetup { .. } => {}, // tiles declared in emit_allocs
            Op::CoopTileZero { name } => {
                let (m, n, _, _, _, _, _, simd) = self.coop_cfg(kernel, name).ok_or_else(|| {
                    Error::UnsupportedOp(format!("cuda: CoopTile `{name}` no Setup"))
                })?;
                let cnm = ct_ident(&coop_c_name(name));
                let local_c =
                    matches!(self.profile.mma, crate::backend::MmaStrategy::SoftwareLocalC);
                if local_c && simd {
                    // Lane-local C: each lane zeros its own slots.
                    let lw = self.profile.lane_width;
                    let per_lane = (m * n).div_ceil(lw).max(1);
                    writeln!(
                        out,
                        "{pad}for (unsigned int _i = 0u; _i < {per_lane}u; _i++) _CTC_lane_{cnm}[_i] = 0.0f;"
                    )
                    .ok();
                } else {
                    let (sid, ssize, _) = coop_scope(simd);
                    let base = coop_base(simd, m * n);
                    writeln!(out, "{pad}for (unsigned int _e = {sid}; _e < {}u; _e += {ssize}) _CTC_{cnm}[{base} + _e] = 0.0f;", m * n).ok();
                }
            },
            // Per Apple MPP headers: metal::extents<int, EI, EO> is {inner,
            // outer}; with tensor_inline the leading-dim stride ld == EI (the
            // inner extent), and the *descriptor flag* (ta/tb) — not the
            // extents — chooses transpose. So stride = ei always.
            Op::CoopTileLoadA { name, ptr_name, ptr_offset, dtype: _, ei, .. } => {
                let (m, _, k, ta, _, _, _, simd) =
                    self.coop_cfg(kernel, name).ok_or_else(|| {
                        Error::UnsupportedOp(format!("cuda: CoopTile `{name}` no Setup"))
                    })?;
                let nm = ct_ident(name);
                let (sid, ssize, _) = coop_scope(simd);
                let base = coop_base(simd, m * k);
                let off = ptr_offset
                    .map(|o| self.vname(Some(o), block, ov))
                    .unwrap_or_else(|| "0".into());
                // A is m×k, leading dim ei. ta=false: ptr[i*ei+j]; ta=true:
                // memory is k×m → ptr[j*ei+i]. (i=_e/k row, j=_e%k col.)
                let src = if ta {
                    format!("(_e % {k}u) * {ei}u + (_e / {k}u)")
                } else {
                    format!("(_e / {k}u) * {ei}u + (_e % {k}u)")
                };
                writeln!(out, "{pad}__syncthreads();").ok();
                writeln!(out, "{pad}for (unsigned int _e = {sid}; _e < {}u; _e += {ssize}) _CTA_{nm}[{base} + _e] = (float)({ptr_name}[{off} + {src}]);", m * k).ok();
            },
            Op::CoopTileLoadB { name, ptr_name, ptr_offset, dtype: _, ei, .. } => {
                let (_, n, k, _, tb, _, _, simd) =
                    self.coop_cfg(kernel, name).ok_or_else(|| {
                        Error::UnsupportedOp(format!("cuda: CoopTile `{name}` no Setup"))
                    })?;
                let nm = ct_ident(name);
                let (sid, ssize, _) = coop_scope(simd);
                let base = coop_base(simd, k * n);
                let off = ptr_offset
                    .map(|o| self.vname(Some(o), block, ov))
                    .unwrap_or_else(|| "0".into());
                // B is k×n, leading dim ei. tb=false: ptr[i*ei+j]; tb=true:
                // memory is n×k → ptr[j*ei+i]. (i=_e/n row, j=_e%n col.)
                let src = if tb {
                    format!("(_e % {n}u) * {ei}u + (_e / {n}u)")
                } else {
                    format!("(_e / {n}u) * {ei}u + (_e % {n}u)")
                };
                writeln!(out, "{pad}for (unsigned int _e = {sid}; _e < {}u; _e += {ssize}) _CTB_{nm}[{base} + _e] = (float)({ptr_name}[{off} + {src}]);", k * n).ok();
            },
            Op::CoopTileRun { name, .. } => {
                let (m, n, k, _, _, _, accum, simd) =
                    self.coop_cfg(kernel, name).ok_or_else(|| {
                        Error::UnsupportedOp(format!("cuda: CoopTile `{name}` no Setup"))
                    })?;
                let nm = ct_ident(name);
                let cnm = ct_ident(&coop_c_name(name));
                let local_c =
                    matches!(self.profile.mma, crate::backend::MmaStrategy::SoftwareLocalC);
                if local_c && simd {
                    // SoftwareLocalC: per-warp lane-local C. Each lane
                    // walks its own `m*n/lw` slots, computing the same
                    // _e = simd_lane + _i*lw as the original cooperative
                    // form. A and B remain shared per-warp.
                    let lw = self.profile.lane_width;
                    let per_lane = (m * n).div_ceil(lw).max(1);
                    let base_a = coop_base(true, m * k);
                    let base_b = coop_base(true, k * n);
                    writeln!(out, "{pad}__syncthreads();").ok();
                    writeln!(out, "{pad}for (unsigned int _li = 0u; _li < {per_lane}u; _li++) {{")
                        .ok();
                    writeln!(out, "{pad}    unsigned int _e = simd_lane + _li * {lw}u;").ok();
                    writeln!(out, "{pad}    if (_e >= {}u) break;", m * n).ok();
                    writeln!(out, "{pad}    unsigned int _i = _e / {n}u, _j = _e % {n}u;").ok();
                    let init =
                        if accum { format!("_CTC_lane_{cnm}[_li]") } else { "0.0f".to_string() };
                    writeln!(out, "{pad}    float _acc = {init};").ok();
                    writeln!(out, "{pad}    for (unsigned int _l = 0u; _l < {k}u; _l++) _acc += _CTA_{nm}[{base_a} + _i * {k}u + _l] * _CTB_{nm}[{base_b} + _l * {n}u + _j];").ok();
                    writeln!(out, "{pad}    _CTC_lane_{cnm}[_li] = _acc;").ok();
                    writeln!(out, "{pad}}}").ok();
                    writeln!(out, "{pad}__syncthreads();").ok();
                } else {
                    let (sid, ssize, _) = coop_scope(simd);
                    let (base_a, base_b, bc) =
                        (coop_base(simd, m * k), coop_base(simd, k * n), coop_base(simd, m * n));
                    writeln!(out, "{pad}__syncthreads();").ok();
                    writeln!(
                        out,
                        "{pad}for (unsigned int _e = {sid}; _e < {}u; _e += {ssize}) {{",
                        m * n
                    )
                    .ok();
                    writeln!(out, "{pad}    unsigned int _i = _e / {n}u, _j = _e % {n}u;").ok();
                    let init = if accum { format!("_CTC_{cnm}[{bc} + _e]") } else { "0.0f".into() };
                    writeln!(out, "{pad}    float _acc = {init};").ok();
                    writeln!(out, "{pad}    for (unsigned int _l = 0u; _l < {k}u; _l++) _acc += _CTA_{nm}[{base_a} + _i * {k}u + _l] * _CTB_{nm}[{base_b} + _l * {n}u + _j];").ok();
                    writeln!(out, "{pad}    _CTC_{cnm}[{bc} + _e] = _acc;").ok();
                    writeln!(out, "{pad}}}").ok();
                    writeln!(out, "{pad}__syncthreads();").ok();
                }
            },
            Op::CoopTileStoreC { name, ptr_name, ptr_offset, dtype, ei, .. } => {
                let (m, n, _, _, _, _, _, simd) = self.coop_cfg(kernel, name).ok_or_else(|| {
                    Error::UnsupportedOp(format!("cuda: CoopTile `{name}` no Setup"))
                })?;
                let cnm = ct_ident(&coop_c_name(name));
                let off = ptr_offset
                    .map(|o| self.vname(Some(o), block, ov))
                    .unwrap_or_else(|| "0".into());
                let ty = cuda_type_name(*dtype);
                let dst = format!("(_e / {n}u) * {ei}u + (_e % {n}u)");
                let local_c =
                    matches!(self.profile.mma, crate::backend::MmaStrategy::SoftwareLocalC);
                if local_c && simd {
                    let lw = self.profile.lane_width;
                    let per_lane = (m * n).div_ceil(lw).max(1);
                    writeln!(out, "{pad}__syncthreads();").ok();
                    writeln!(out, "{pad}for (unsigned int _li = 0u; _li < {per_lane}u; _li++) {{")
                        .ok();
                    writeln!(out, "{pad}    unsigned int _e = simd_lane + _li * {lw}u;").ok();
                    writeln!(out, "{pad}    if (_e >= {}u) break;", m * n).ok();
                    writeln!(
                        out,
                        "{pad}    {ptr_name}[{off} + {dst}] = ({ty})(_CTC_lane_{cnm}[_li]);"
                    )
                    .ok();
                    writeln!(out, "{pad}}}").ok();
                } else {
                    let (sid, ssize, _) = coop_scope(simd);
                    let base = coop_base(simd, m * n);
                    let _ = m;
                    writeln!(out, "{pad}__syncthreads();").ok();
                    writeln!(out, "{pad}for (unsigned int _e = {sid}; _e < {}u; _e += {ssize}) {ptr_name}[{off} + {dst}] = ({ty})(_CTC_{cnm}[{base} + _e]);", m * n).ok();
                }
            },
            // ── Control flow (nested-block recursion) ──────────────────
            Op::Loop { var, start, end, step, body } => {
                let s = self.vname(Some(*start), block, ov);
                let e = self.vname(Some(*end), block, ov);
                let st = self.vname(Some(*step), block, ov);
                let lv = format!("i_{}", var.as_u32());
                writeln!(out, "{pad}for (unsigned int {lv} = {s}; {lv} < {e}; {lv} += {st}) {{")
                    .ok();
                if let Some(base_b) = kernel.blocks.get(body) {
                    let mut child = self.child_ov(block, ov);
                    // The loop induction var is referenced inside the body by
                    // two macro-assigned magic ValueIds (see msl emit_block).
                    child.insert(ValueId::new(0xC000_0000 | var.as_u32()), lv.clone());
                    child.insert(ValueId::new(var.as_u32() + 0x4000_0000), lv.clone());
                    self.emit_ops(base_b, kernel, &child, out)?;
                }
                writeln!(out, "{pad}}}").ok();
            },
            Op::If { cond, then_block, else_block } => {
                let c = self.vname(Some(*cond), block, ov);
                writeln!(out, "{pad}if ({c}) {{").ok();
                if let Some(tb) = kernel.blocks.get(then_block) {
                    let child = self.child_ov(block, ov);
                    self.emit_ops(tb, kernel, &child, out)?;
                }
                if let Some(ebid) = else_block {
                    writeln!(out, "{pad}}} else {{").ok();
                    if let Some(eb) = kernel.blocks.get(ebid) {
                        let child = self.child_ov(block, ov);
                        self.emit_ops(eb, kernel, &child, out)?;
                    }
                }
                writeln!(out, "{pad}}}").ok();
            },
            other => {
                return Err(Error::UnsupportedOp(format!(
                    "cuda: op {} not supported yet",
                    op_variant_name(other)
                )));
            },
        }
        Ok(())
    }

    /// Two-level threadgroup reduction: warp shuffle (`__shfl_down_sync`)
    /// then a `__shared__` tree across warps — the CUDA analog of
    /// `msl::reduce`'s `simd_sum` + threadgroup-memory path. Lane width 32
    /// matches Metal's simdgroup (the lucky structural match). Assumes
    /// `blockDim.x` is a multiple of 32 (Phase-2 constraint; partial-warp
    /// masking is a Phase-3 refinement).
    fn emit_reduce_tree(&self, result: &str, input: &str, kind: ReduceKind, out: &mut String) {
        let pad = "    ";
        let lw = self.profile.lane_width;
        let half = lw / 2;
        let init = reduce_init(kind);
        let buf = format!("{result}_sg");
        writeln!(out, "{pad}__shared__ float {buf}[32];").ok();
        writeln!(out, "{pad}float {result};").ok();
        writeln!(out, "{pad}{{").ok();
        // Phase 1: intra-warp reduction.
        writeln!(out, "{pad}    float _sv = (float)({input});").ok();
        writeln!(out, "{pad}    for (int _o = {half}; _o > 0; _o >>= 1) {{").ok();
        writeln!(out, "{pad}        float _ov = __shfl_down_sync(0xffffffffu, _sv, _o);").ok();
        writeln!(out, "{pad}        _sv = {};", reduce_combine(kind, "_sv", "_ov")).ok();
        writeln!(out, "{pad}    }}").ok();
        // Phase 2: lane 0 of each warp publishes its total.
        writeln!(out, "{pad}    if (simd_lane == 0u) {buf}[simd_group] = _sv;").ok();
        writeln!(out, "{pad}    __syncthreads();").ok();
        // Phase 3: warp 0 reduces the per-warp totals and broadcasts via [0].
        writeln!(out, "{pad}    if (simd_group == 0u) {{").ok();
        writeln!(out, "{pad}        float _wv = simd_lane < n_simd ? {buf}[simd_lane] : {init};")
            .ok();
        writeln!(out, "{pad}        for (int _o = {half}; _o > 0; _o >>= 1) {{").ok();
        writeln!(out, "{pad}            float _ov = __shfl_down_sync(0xffffffffu, _wv, _o);").ok();
        writeln!(out, "{pad}            _wv = {};", reduce_combine(kind, "_wv", "_ov")).ok();
        writeln!(out, "{pad}        }}").ok();
        writeln!(out, "{pad}        if (simd_lane == 0u) {buf}[0] = _wv;").ok();
        writeln!(out, "{pad}    }}").ok();
        writeln!(out, "{pad}    __syncthreads();").ok();
        if kind == ReduceKind::Mean {
            writeln!(out, "{pad}    {result} = {buf}[0] / (float)lsize;").ok();
        } else {
            writeln!(out, "{pad}    {result} = {buf}[0];").ok();
        }
        // Loop-reentry guard: when this Reduce sits inside a Loop, warp 0
        // can start the NEXT iteration and overwrite {buf} before a lagging
        // warp has read this iteration's {buf}[0].
        writeln!(out, "{pad}    __syncthreads();").ok();
        writeln!(out, "{pad}}}").ok();
    }

    /// Find the `CoopTileSetup` config for a named GEMM op:
    /// (m, n, k, ta, tb, tc, accumulate, simdgroup_scope).
    #[allow(clippy::type_complexity)]
    fn coop_cfg(
        &self,
        kernel: &Kernel,
        name: &str,
    ) -> Option<(u32, u32, u32, bool, bool, bool, bool, bool)> {
        for blk in std::iter::once(&kernel.body).chain(kernel.blocks.values()) {
            for op in &blk.ops {
                if let Op::CoopTileSetup {
                    name: nm, m, n, k, ta, tb, tc, acc_mode, exec_scope, ..
                } = op
                    && nm == name
                {
                    return Some((
                        *m,
                        *n,
                        *k,
                        *ta,
                        *tb,
                        *tc,
                        matches!(acc_mode, CoopTileAccMode::MultiplyAccumulate),
                        matches!(exec_scope, CoopTileScope::SimdGroup),
                    ));
                }
            }
        }
        None
    }

    fn cuda_unary(&self, op: UnaryOpKind, arg: &str) -> String {
        use UnaryOpKind::*;
        // Precise-math overrides (HIP enables these via
        // `TargetProfile::precise_simd_sum`; CUDA defaults skip them).
        // Recip/Rsqrt always have a float result so the explicit
        // `(float)` cast on the arg is safe (Recip's 1.0f literal also
        // pins overload resolution to the float overload).
        if self.profile.precise_simd_sum {
            match op {
                Recip => return format!("iron_fdiv(1.0f, (float)({arg}))"),
                Rsqrt => return format!("iron_rsqrt((float)({arg}))"),
                Exp => return format!("iron_expf((float)({arg}))"),
                Log => return format!("iron_logf((float)({arg}))"),
                _ => {},
            }
        }
        match op {
            Neg => format!("(-{arg})"),
            Recip => format!("(1.0f / {arg})"),
            // sign(x): -1/0/+1 (matches Metal `sign`, incl. 0 → 0).
            // `copysignf` would map 0 → +1, so emit the explicit form.
            Sign =>
                format!("((float)({arg}) > 0.0f ? 1.0f : ((float)({arg}) < 0.0f ? -1.0f : 0.0f))"),
            // Block-scaled-quant decode helpers (preamble __device__ fns).
            _ => format!("{}({arg})", self.profile.unary_intrinsic(op)),
        }
    }
}

impl CodegenBackend for CudaGenerator {
    fn target(&self) -> Target { Target::Cuda }

    fn profile(&self) -> &TargetProfile { &self.profile }

    fn generate(&self, kernel: &Kernel) -> Result<String> {
        // Resolve cross-kernel calls (Op::KernelCall) via the backend-neutral
        // inline pass. Non-call kernels are unaffected; on failure we fall
        // back to the raw IR.
        let mut inlined = kernel.clone();
        let k: &Kernel = match crate::passes::run_passes(&mut inlined, &[Box::new(
            crate::passes::kernel_inline::KernelInlinePass,
        )]) {
            Ok(()) => &inlined,
            Err(_) => kernel,
        };
        let mut out = String::new();
        out.push_str(CUDA_PREAMBLE);
        self.emit_signature(k, &mut out)?;
        self.emit_body(k, &mut out)?;
        Ok(out)
    }
}

/// DType → CUDA C++ scalar type name.
pub fn cuda_type_name(dt: DType) -> &'static str {
    match dt {
        DType::F32 => "float",
        DType::F16 => "__half",
        DType::BF16 => "__nv_bfloat16",
        DType::I32 => "int",
        DType::U32 => "unsigned int",
        DType::I8 => "signed char",
        DType::U8 => "unsigned char",
        DType::I4 => "signed char", // packed; sub-byte handled in decode helpers
        DType::U16 => "unsigned short",
        DType::I64 => "long long",
        DType::U64 => "unsigned long long",
        DType::Bool => "bool",
    }
}

/// BinOp → CUDA expression (infix for arithmetic/compare/bitwise,
/// function-call for the few that need it). Mirrors `BinOpKind::msl_symbol`
/// semantics with CUDA intrinsic names.
fn cuda_binop(op: BinOpKind, l: &str, r: &str) -> String {
    use BinOpKind::*;
    match op {
        Add => format!("{l} + {r}"),
        Sub => format!("{l} - {r}"),
        Mul => format!("{l} * {r}"),
        Div => format!("{l} / {r}"),
        // fmaxf/fminf with float casts: plain `max`/`min` is ambiguous on
        // `auto`-typed operands and missing for __half/__nv_bfloat16.
        Max => format!("fmaxf((float)({l}), (float)({r}))"),
        Min => format!("fminf((float)({l}), (float)({r}))"),
        Pow => format!("powf({l}, {r})"),
        ATan2 => format!("atan2f({l}, {r})"),
        Rem => format!("fmodf({l}, {r})"),
        Mod => format!("({l} % {r})"),
        And => format!("({l} && {r})"),
        Or => format!("({l} || {r})"),
        Xor => format!("((bool){l} != (bool){r})"),
        BitAnd => format!("({l} & {r})"),
        BitOr => format!("({l} | {r})"),
        BitXor => format!("({l} ^ {r})"),
        Shl => format!("({l} << {r})"),
        Shr => format!("({l} >> {r})"),
        CmpLt => format!("({l} < {r})"),
        CmpGt => format!("({l} > {r})"),
        CmpLe => format!("({l} <= {r})"),
        CmpGe => format!("({l} >= {r})"),
        CmpEq => format!("({l} == {r})"),
        CmpNe => format!("({l} != {r})"),
    }
}

/// Format an f64 IR literal as a valid CUDA C++ `float` literal. Integral
/// values need an explicit decimal point (`1` → `1.0f`; bare `1f` is not a
/// C++ literal), and non-finite values have no literal form at all.
fn fmt_f32_lit(v: f64) -> String {
    if !v.is_finite() {
        if v.is_nan() {
            return "(IRON_INF - IRON_INF)".to_string();
        }
        return if v > 0.0 { "IRON_INF".to_string() } else { "(-IRON_INF)".to_string() };
    }
    if v.fract() == 0.0 { format!("{v:.1}f") } else { format!("{v}f") }
}

/// Identity / initial accumulator value for a reduction kind.
fn reduce_init(kind: ReduceKind) -> &'static str {
    match kind {
        ReduceKind::Sum | ReduceKind::Mean => "0.0f",
        ReduceKind::Max => "(-IRON_INF)",
        ReduceKind::Min => "IRON_INF",
        ReduceKind::Product => "1.0f",
    }
}

/// Binary combine for a reduction kind: `combine(a, b)` as a CUDA expr.
fn reduce_combine(kind: ReduceKind, a: &str, b: &str) -> String {
    match kind {
        ReduceKind::Sum | ReduceKind::Mean => format!("{a} + {b}"),
        ReduceKind::Max => format!("fmaxf({a}, {b})"),
        ReduceKind::Min => format!("fminf({a}, {b})"),
        ReduceKind::Product => format!("{a} * {b}"),
    }
}

/// Does the kernel contain a threadgroup-scope `Op::Reduce` (the only op
/// that needs the `n_simd≥1` freeze guard)?
fn kernel_has_reduce(kernel: &Kernel) -> bool {
    std::iter::once(&kernel.body)
        .chain(kernel.blocks.values())
        .any(|b| b.ops.iter().any(|op| matches!(op, Op::Reduce { .. })))
}

/// Per-warp shared-tile name for a simdgroup_matrix value.
fn sgm_name(v: ValueId) -> String { format!("_SGM_{}", v.as_u32()) }

/// The C-accumulator group name for a CoopTile setup: a `*_acc`
/// (multiply-accumulate) setup shares its C tile with the base setup
/// (e.g. `qk_acc` accumulates onto `qk`'s C across head_dim chunks).
fn coop_c_name(name: &str) -> String { name.strip_suffix("_acc").unwrap_or(name).to_string() }

/// Sanitize a CoopTile name into a valid C identifier suffix.
fn ct_ident(name: &str) -> String {
    name.chars().map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' }).collect()
}

/// Cooperative-scope iteration vars: (thread-id, scope-size, barrier).
fn coop_scope(simd: bool) -> (&'static str, &'static str, &'static str) {
    if simd { ("simd_lane", "32u", "__syncwarp();") } else { ("tid", "lsize", "__syncthreads();") }
}

/// Base offset into a per-scope shared tile of `tile` elements.
fn coop_base(simd: bool, tile: u32) -> String {
    if simd { format!("simd_group * {tile}u") } else { "0u".to_string() }
}

/// Does the kernel use any simdgroup-matrix op (drives the lane-coord
/// preamble + shared tile allocation)?
fn uses_simdgroup(kernel: &Kernel) -> bool {
    std::iter::once(&kernel.body).chain(kernel.blocks.values()).any(|b| {
        b.ops.iter().any(|op| {
            matches!(
                op,
                Op::SimdgroupAlloc { .. }
                    | Op::SimdgroupLoad { .. }
                    | Op::SimdgroupMatMul { .. }
                    | Op::SimdgroupElemLoad { .. }
                    | Op::SimdgroupElemStore { .. }
            )
        })
    })
}

/// Variant name of an `Op` (Debug-derived), for diagnostics.
fn op_variant_name(op: &Op) -> String {
    let dbg = format!("{op:?}");
    dbg.split([' ', '{', '(']).next().unwrap_or("?").to_string()
}

#[cfg(test)]
mod tests {
    use wh_iron_core::{
        ir::{BinOpKind, IndexExpr, Op},
        shape::Shape,
    };

    use super::*;

    fn vector_add_ir() -> Kernel {
        // Mirrors the codegen MSL test's `vector_add`: out[i] = a[i] + b[i].
        let mut k = Kernel::new("vector_add");
        for (name, is_out) in [("a", false), ("b", false), ("c", true)] {
            k.params.push(Param {
                name: name.into(),
                dtype: DType::F32,
                shape: Shape::scalar(),
                is_output: is_out,
                kind: ParamKind::Tensor,
            });
        }
        k.body.push_op(Op::ProgramId { axis: 0 }, ValueId::new(0));
        k.body.name_value(ValueId::new(0), "idx");
        k.body.push_op(
            Op::Load {
                src: "a".into(),
                indices: vec![IndexExpr::Value(ValueId::new(0))],
                mask: None,
                other: None,
            },
            ValueId::new(1),
        );
        k.body.name_value(ValueId::new(1), "x");
        k.body.push_op(
            Op::Load {
                src: "b".into(),
                indices: vec![IndexExpr::Value(ValueId::new(0))],
                mask: None,
                other: None,
            },
            ValueId::new(2),
        );
        k.body.name_value(ValueId::new(2), "y");
        k.body.push_op(
            Op::BinOp { op: BinOpKind::Add, lhs: ValueId::new(1), rhs: ValueId::new(2) },
            ValueId::new(3),
        );
        k.body.name_value(ValueId::new(3), "sum");
        k.body.push_op_no_result(Op::Store {
            dst: "c".into(),
            indices: vec![IndexExpr::Value(ValueId::new(0))],
            value: ValueId::new(3),
            mask: None,
        });
        k
    }

    #[test]
    fn emits_vector_add_cuda() {
        let g = CudaGenerator::new();
        let src = g.generate(&vector_add_ir()).unwrap();
        // Signature: pointers + synthetic bounds param.
        assert!(src.contains("extern \"C\" __global__ void vector_add("));
        assert!(src.contains("const float* __restrict__ a"));
        assert!(src.contains("const float* __restrict__ b"));
        assert!(src.contains("float* __restrict__ c"));
        assert!(src.contains(&format!("unsigned int {N_ELEMS_PARAM}")));
        // Body: global tid + guard + the add.
        assert!(src.contains("blockIdx.x * blockDim.x + threadIdx.x"));
        assert!(src.contains(&format!("if (_gtid >= {N_ELEMS_PARAM}) return;")));
        assert!(src.contains("unsigned int v_idx_0 = _gtid;"));
        assert!(src.contains("auto v_x_1 = __ldg(&a[v_idx_0]);"));
        assert!(src.contains("auto v_y_2 = __ldg(&b[v_idx_0]);"));
        assert!(src.contains("auto v_sum_3 = v_x_1 + v_y_2;"));
        assert!(src.contains("c[v_idx_0] = v_sum_3;"));
    }

    fn row_reduce_ir() -> Kernel {
        // out[row] = sum(inp[row*n .. row*n+n]) — Reduction mode.
        let mut k = Kernel::new("row_reduce_sum");
        k.mode = KernelMode::Reduction;
        k.params.push(Param {
            name: "inp".into(),
            dtype: DType::F32,
            shape: Shape::scalar(),
            is_output: false,
            kind: ParamKind::Tensor,
        });
        k.params.push(Param {
            name: "out".into(),
            dtype: DType::F32,
            shape: Shape::scalar(),
            is_output: true,
            kind: ParamKind::Tensor,
        });
        k.constexprs.push(wh_iron_core::ir::ConstExprDecl {
            name: wh_iron_core::constexpr::ConstExpr::new("n"),
            dtype: DType::U32,
            value: None,
        });
        let (row, nv, rs, re, acc, res) = (
            ValueId::new(0),
            ValueId::new(1),
            ValueId::new(2),
            ValueId::new(3),
            ValueId::new(4),
            ValueId::new(5),
        );
        k.body.push_op(Op::ProgramId { axis: 0 }, row);
        k.body.name_value(row, "row");
        k.body.push_op(Op::Load { src: "n".into(), indices: vec![], mask: None, other: None }, nv);
        k.body.push_op(Op::BinOp { op: BinOpKind::Mul, lhs: row, rhs: nv }, rs);
        k.body.name_value(rs, "rs");
        k.body.push_op(Op::BinOp { op: BinOpKind::Add, lhs: rs, rhs: nv }, re);
        k.body.name_value(re, "re");
        k.body.push_op(
            Op::StrideReduce {
                src: "inp".into(),
                offset: rs,
                stride: nv,
                end: re,
                op: ReduceKind::Sum,
                dtype: DType::F32,
                transform: None,
                secondary_src: None,
                secondary_base: None,
            },
            acc,
        );
        k.body.name_value(acc, "acc");
        k.body.push_op(Op::Reduce { value: acc, axis: 0, op: ReduceKind::Sum }, res);
        k.body.name_value(res, "result");
        k.body.push_op_no_result(Op::Store {
            dst: "out".into(),
            indices: vec![IndexExpr::Value(row)],
            value: res,
            mask: None,
        });
        k
    }

    #[test]
    fn emits_row_reduce_cuda() {
        let src = CudaGenerator::new().generate(&row_reduce_ir()).unwrap();
        // Reduction signature: no synthetic _n_elems param.
        assert!(src.contains("extern \"C\" __global__ void row_reduce_sum("));
        assert!(src.contains("unsigned int n"));
        assert!(!src.contains(N_ELEMS_PARAM));
        // Reduction preamble (block-per-row, warp = 32 lanes, ids from the
        // flattened in-block thread index).
        assert!(src.contains("const unsigned int tgid_x    = blockIdx.x;"));
        assert!(src.contains("const unsigned int _ltid     = (threadIdx.z * blockDim.y + threadIdx.y) * blockDim.x + threadIdx.x;"));
        assert!(
            src.contains("const unsigned int lsize     = blockDim.x * blockDim.y * blockDim.z;")
        );
        assert!(src.contains("const unsigned int n_simd    = lsize / 32u;"));
        assert!(src.contains("const unsigned int simd_lane  = _ltid % 32u;"));
        // Per-thread grid-stride accumulation.
        assert!(src.contains("for (unsigned int _i = v_rs_2 + tid; _i < v_re_3; _i += lsize)"));
        // Two-level tree: warp shuffle + shared mem + barriers.
        assert!(src.contains("__shfl_down_sync(0xffffffffu"));
        assert!(src.contains("__shared__ float v_result_5_sg[32];"));
        assert!(src.contains("__syncthreads();"));
        assert!(src.contains("out[v_row_0] = v_result_5;"));
    }

    #[test]
    fn rejects_unsupported_mode() {
        let mut k = vector_add_ir();
        k.mode = KernelMode::Tile2D;
        assert!(CudaGenerator::new().generate(&k).is_err());
    }

    #[test]
    fn float_literals_are_valid_cpp() {
        assert_eq!(fmt_f32_lit(1.0), "1.0f");
        assert_eq!(fmt_f32_lit(-2.0), "-2.0f");
        assert_eq!(fmt_f32_lit(0.5), "0.5f");
        assert_eq!(fmt_f32_lit(f64::INFINITY), "IRON_INF");
        assert_eq!(fmt_f32_lit(f64::NEG_INFINITY), "(-IRON_INF)");
    }

    #[test]
    fn cuda_generator_reports_cuda_target_and_profile() {
        let g = CudaGenerator::new();
        assert_eq!(g.target(), Target::Cuda);
        assert_eq!(g.profile().shared_mem_kw, "__shared__");
        assert_eq!(g.profile().lane_width, 32);
    }
}
