//! Copyright 2026 0xClandestine, Ekryski, TheTom, Ambisphaeric
//! SPDX-License-Identifier: Apache-2.0
//! `tile init` — Scaffold a new MetalTile kernel project.
//!
//! Creates the project layout in the current directory (or `--name <dir>`):
//!
//! ```text
//! <name>/
//!   Cargo.toml          (workspace-aware package, depends on ffai-kernels-std)
//!   src/
//!     lib.rs            (sample #[kernel] and #[bench_kernel])
//!   tile.toml           (layered tile CLI config: sub-tables, profiles, extends)
//! ```

use std::path::Path;

use crate::{
    CliError,
    InitArgs,
    term::{Color, Style, paint_stderr, paint_stdout},
};

/// `TileCommand` wrapper for `tile init`.
pub struct InitCommand<'a>(pub &'a InitArgs);

impl<'a> super::TileCommand for InitCommand<'a> {
    fn run(&self, _harness: &crate::harness::Harness) -> Result<(), crate::CliError> { run(self.0) }
}

pub fn run(args: &InitArgs) -> Result<(), CliError> {
    let name = &args.name;
    let root = Path::new(name.as_str());

    if root.exists() && !args.force {
        eprintln!(
            "{} directory '{}' already exists. Use --force to overwrite.",
            paint_stderr("error:", Style::new().fg(Color::Red).bold()),
            name,
        );
        return Err(CliError::Other(format!("'{name}' already exists")));
    }

    // Create directory tree.
    let src_dir = root.join("src");
    let bin_dir = root.join("bin");
    std::fs::create_dir_all(&src_dir).map_err(CliError::Io)?;
    std::fs::create_dir_all(&bin_dir).map_err(CliError::Io)?;

    // Cargo.toml
    let mt_version = env!("CARGO_PKG_VERSION");
    let cargo_toml = format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2024"

[dependencies]
ffai-kernels = "{mt_version}"
ffai-kernels-std = "{mt_version}"

# Hidden subprocess binary used by the `tile` CLI for kernel discovery.
# Install to project bin/ with: cargo install --path . --root .
[[bin]]
name = "__tile_runner"
path = "bin/__tile_runner.rs"
"#
    );
    write_file(&root.join("Cargo.toml"), &cargo_toml)?;

    // src/lib.rs — sample kernel
    let lib_rs = r#"//! Sample MetalTile kernel project generated by `tile init`.
use ffai_kernels_std::prelude::*;

/// Element-wise ReLU: out[i] = max(0, src[i]).
#[kernel]
pub fn mt_relu<T: Float>(src: &[T], out: &mut [T], n: uint) {
    let i = program_id::<0>();
    if i < n {
        out[i] = src[i].max(T::zero());
    }
}

#[bench_kernel(name = "mt_relu", dtypes = [f32, f16, bf16])]
fn bench_relu(dt: DType) -> BenchSetup {
    let n = 1 << 20;
    BenchSetup::elementwise("mt_relu", n, dt)
}
"#;
    write_file(&src_dir.join("lib.rs"), lib_rs)?;

    // bin/__tile_runner.rs — subprocess entry point for the tile CLI.
    // After `cargo install --path . --root .`, the binary lands in bin/ where
    // `tile bench/test/inspect` will find and spawn it.
    let runner_rs = r#"fn main() {
    let args = match ffai_kernels::runner::RunnerArgs::from_env_args() {
        Ok(a) => a,
        Err(e) => {
            eprintln!("__tile_runner: {e}");
            std::process::exit(2);
        },
    };
    std::process::exit(if ffai_kernels::runner::RunnerHarness::run(&args) { 0 } else { 1 });
}
"#;
    write_file(&bin_dir.join("__tile_runner.rs"), runner_rs)?;

    // tile.toml — project config
    let tile_toml = r#"# tile CLI configuration for this project.
# Values here are overridden by TILE_* env vars and CLI flags.
# Select a named profile with --profile <name> or TILE_PROFILE=<name>.

# Verbosity: 0 = quiet, 1 = profile columns (-v), 2 = timing columns (-vv).
verbose = 0

[bench]
# Number of timed iterations per kernel (after warmup).
runs = 3
# Number of warmup dispatches before timing begins.
warmup_runs = 1

[build]
# xcrun SDK for Metal compilation.
sdk = "macosx"
# Dtypes compiled by default when --dtypes is not passed.
default_dtypes = ["f32", "f16", "bf16"]

[runner]
# Path to the __tile_runner subprocess binary.
# Run `cargo install --path . --root .` to install it here.
binary = "bin/__tile_runner"

# Example CI profile — select with: tile bench --profile ci
# [profiles.ci]
# [profiles.ci.bench]
# runs = 5
# warmup_runs = 2
"#;
    write_file(&root.join("tile.toml"), tile_toml)?;

    // Success banner.
    println!("{}", paint_stdout("tile init", Style::new().fg(Color::Cyan).bold()));
    println!();
    let ck = paint_stdout("✓", Style::new().fg(Color::Green).bold());
    println!(
        "  {ck}  {}",
        paint_stdout(format!("Created project '{name}'"), Style::new().fg(Color::BrightWhite),)
    );
    println!("  {}  {}/Cargo.toml", paint_stdout("   ", Style::new()), name,);
    println!("  {}  {}/src/lib.rs", paint_stdout("   ", Style::new()), name,);
    println!("  {}  {}/bin/__tile_runner.rs", paint_stdout("   ", Style::new()), name,);
    println!("  {}  {}/tile.toml", paint_stdout("   ", Style::new()), name,);
    println!();
    println!(
        "  {}",
        paint_stdout(
            format!("cd {name} && cargo install --path . --root . && tile bench"),
            Style::new().fg(Color::BrightBlack),
        )
    );
    println!();

    Ok(())
}

fn write_file(path: &Path, content: &str) -> Result<(), CliError> {
    std::fs::write(path, content).map_err(CliError::Io)
}
